# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FlhsICN3uvURqA0irZkAoSdRgFnRfhzu
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

cars=[]
                                    #BMW
for i in range (1,10):
    url=f'https://www.otomoto.pl/osobowe/bmw?page=i'
    response=requests.get(url)
    response=response.content
    soup=BeautifulSoup(response,'html.parser')
    div=soup.find('div',class_="ooa-r53y0q ezh3mkl11")
    articles=div.find_all('article',class_='ooa-yca59n eszxync0')
    for article in articles:
                                               #name
        name=article.find('a').text
        print(name)
                                               #space
        space=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        space=space[:9]
        print(space)
                                               # kilometers
        km=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        km=km[13:18]
        print(km)
                                               #price
        price=article.find('h3',class_='eszxync16 ooa-1n2paoq er34gjf0').text
        price+=article.find('p',class_='eszxync17 ooa-8vn6i7 er34gjf0').text
        print(price)
      #                                          #kilometrage
        kilometrage=article.find('dd',class_='ooa-1omlbtp eszxync13').text
        print(kilometrage)
                                               #essence

        essence=article.find('dl', class_="ooa-1omlbtp eszxync13")
        essence=article.find(attrs={'data-parameter':"fuel_type"}).text.strip()
        print(essence)
                                               # gearbox_type==manuelle ou automatique

        gearbox_type=article.find('dl', class_="ooa-1omlbtp eszxync13")
        gearbox_type=article.find(attrs={'data-parameter':'gearbox'}).text.strip()
        print(gearbox_type)
                                      # year

        year=article.find('dl', class_="ooa-1omlbtp eszxync13")
        year=article.find(attrs={'data-parameter':'year'}).text.strip()
        print(year)

        cars.append([name,space,km,price,kilometrage,essence,gearbox_type,year])

                                          #FIAT
for i in range (1,10):
    url=f'https://www.otomoto.pl/osobowe/fiat?page=i'
    response=requests.get(url)
    response=response.content
    soup=BeautifulSoup(response,'html.parser')
    div=soup.find('div',class_="ooa-r53y0q ezh3mkl11")
    articles=div.find_all('article',class_='ooa-yca59n eszxync0')
    for article in articles:
                                               #name
        name=article.find('a').text
        print(name)
                                               #space
        space=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        space=space[:9]
        print(space)
                                               # kilometers
        km=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        km=km[13:18]
        print(km)
                                               #price
        price=article.find('h3',class_='eszxync16 ooa-1n2paoq er34gjf0').text
        price+=article.find('p',class_='eszxync17 ooa-8vn6i7 er34gjf0').text
        print(price)
      #                                          #kilometrage
        kilometrage=article.find('dd',class_='ooa-1omlbtp eszxync13').text
        print(kilometrage)
                                               #essence

        essence=article.find('dl', class_="ooa-1omlbtp eszxync13")
        essence=article.find(attrs={'data-parameter':"fuel_type"}).text.strip()
        print(essence)
                                               # gearbox_type==manuelle ou automatique

        gearbox_type=article.find('dl', class_="ooa-1omlbtp eszxync13")
        gearbox_type=article.find(attrs={'data-parameter':'gearbox'}).text.strip()
        print(gearbox_type)
                                      # year

        year=article.find('dl', class_="ooa-1omlbtp eszxync13")
        year=article.find(attrs={'data-parameter':'year'}).text.strip()
        print(year)

        cars.append([name,space,km,price,kilometrage,essence,gearbox_type,year])

                                                                   #AUDI
for i in range (1,10):
    url=f'https://www.otomoto.pl/osobowe/audi?page=i'
    response=requests.get(url)
    response=response.content
    soup=BeautifulSoup(response,'html.parser')
    div=soup.find('div',class_="ooa-r53y0q ezh3mkl11")
    articles=div.find_all('article',class_='ooa-yca59n eszxync0')
    for article in articles:
                                               #name
        name=article.find('a').text
        print(name)
                                               #space
        space=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        space=space[:9]
        print(space)
                                               # kilometers
        km=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        km=km[13:18]
        print(km)
                                               #price
        price=article.find('h3',class_='eszxync16 ooa-1n2paoq er34gjf0').text
        price+=article.find('p',class_='eszxync17 ooa-8vn6i7 er34gjf0').text
        print(price)
      #                                          #kilometrage
        kilometrage=article.find('dd',class_='ooa-1omlbtp eszxync13').text
        print(kilometrage)
                                               #essence

        essence=article.find('dl', class_="ooa-1omlbtp eszxync13")
        essence=article.find(attrs={'data-parameter':"fuel_type"}).text.strip()
        print(essence)
                                               # gearbox_type==manuelle ou automatique

        gearbox_type=article.find('dl', class_="ooa-1omlbtp eszxync13")
        gearbox_type=article.find(attrs={'data-parameter':'gearbox'}).text.strip()
        print(gearbox_type)
                                      # year

        year=article.find('dl', class_="ooa-1omlbtp eszxync13")
        year=article.find(attrs={'data-parameter':'year'}).text.strip()
        print(year)

        cars.append([name,space,km,price,kilometrage,essence,gearbox_type,year])

                                                   #citroen
for i in range (1,10):
    url=f'https://www.otomoto.pl/osobowe/citroen?page=i'
    response=requests.get(url)
    response=response.content
    soup=BeautifulSoup(response,'html.parser')
    div=soup.find('div',class_="ooa-r53y0q ezh3mkl11")
    articles=div.find_all('article',class_='ooa-yca59n eszxync0')
    for article in articles:
                                               #name
        name=article.find('a').text
        print(name)
                                               #space
        space=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        space=space[:9]
        print(space)
                                               # kilometers
        km=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        km=km[13:18]
        print(km)
                                               #price
        price=article.find('h3',class_='eszxync16 ooa-1n2paoq er34gjf0').text
        price+=article.find('p',class_='eszxync17 ooa-8vn6i7 er34gjf0').text
        print(price)
      #                                          #kilometrage
        kilometrage=article.find('dd',class_='ooa-1omlbtp eszxync13').text
        print(kilometrage)
                                               #essence

        essence=article.find('dl', class_="ooa-1omlbtp eszxync13")
        essence=article.find(attrs={'data-parameter':"fuel_type"}).text.strip()
        print(essence)
                                               # gearbox_type==manuelle ou automatique

        gearbox_type=article.find('dl', class_="ooa-1omlbtp eszxync13")
        gearbox_type=article.find(attrs={'data-parameter':'gearbox'}).text.strip()
        print(gearbox_type)
                                      # year

        year=article.find('dl', class_="ooa-1omlbtp eszxync13")
        year=article.find(attrs={'data-parameter':'year'}).text.strip()
        print(year)

        cars.append([name,space,km,price,kilometrage,essence,gearbox_type,year])

                                                    #FORD
for i in range (1,10):
    url=f'https://www.otomoto.pl/osobowe/ford?page=i'
    response=requests.get(url)
    response=response.content
    soup=BeautifulSoup(response,'html.parser')
    div=soup.find('div',class_="ooa-r53y0q ezh3mkl11")
    articles=div.find_all('article',class_='ooa-yca59n eszxync0')
    for article in articles:
                                               #name
        name=article.find('a').text
        print(name)
                                               #space
        space=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        space=space[:9]
        print(space)
                                               # kilometers
        km=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        km=km[13:18]
        print(km)
                                               #price
        price=article.find('h3',class_='eszxync16 ooa-1n2paoq er34gjf0').text
        price+=article.find('p',class_='eszxync17 ooa-8vn6i7 er34gjf0').text
        print(price)
      #                                          #kilometrage
        kilometrage=article.find('dd',class_='ooa-1omlbtp eszxync13').text
        print(kilometrage)
                                               #essence

        essence=article.find('dl', class_="ooa-1omlbtp eszxync13")
        essence=article.find(attrs={'data-parameter':"fuel_type"}).text.strip()
        print(essence)
                                               # gearbox_type==manuelle ou automatique

        gearbox_type=article.find('dl', class_="ooa-1omlbtp eszxync13")
        gearbox_type=article.find(attrs={'data-parameter':'gearbox'}).text.strip()
        print(gearbox_type)
                                      # year

        year=article.find('dl', class_="ooa-1omlbtp eszxync13")
        year=article.find(attrs={'data-parameter':'year'}).text.strip()
        print(year)

        cars.append([name,space,km,price,kilometrage,essence,gearbox_type,year])

                                                      #HYUNDAI
for i in range (1,10):
    url=f'https://www.otomoto.pl/osobowe/hyundai?page=i'
    response=requests.get(url)
    response=response.content
    soup=BeautifulSoup(response,'html.parser')
    div=soup.find('div',class_="ooa-r53y0q ezh3mkl11")
    articles=div.find_all('article',class_='ooa-yca59n eszxync0')
    for article in articles:
                                               #name
        name=article.find('a').text
        print(name)
                                               #space
        space=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        space=space[:9]
        print(space)
                                               # kilometers
        km=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        km=km[13:18]
        print(km)
                                               #price
        price=article.find('h3',class_='eszxync16 ooa-1n2paoq er34gjf0').text
        price+=article.find('p',class_='eszxync17 ooa-8vn6i7 er34gjf0').text
        print(price)
      #                                          #kilometrage
        kilometrage=article.find('dd',class_='ooa-1omlbtp eszxync13').text
        print(kilometrage)
                                               #essence

        essence=article.find('dl', class_="ooa-1omlbtp eszxync13")
        essence=article.find(attrs={'data-parameter':"fuel_type"}).text.strip()
        print(essence)
                                               # gearbox_type==manuelle ou automatique

        gearbox_type=article.find('dl', class_="ooa-1omlbtp eszxync13")
        gearbox_type=article.find(attrs={'data-parameter':'gearbox'}).text.strip()
        print(gearbox_type)
                                      # year

        year=article.find('dl', class_="ooa-1omlbtp eszxync13")
        year=article.find(attrs={'data-parameter':'year'}).text.strip()
        print(year)

        cars.append([name,space,km,price,kilometrage,essence,gearbox_type,year])

                                               #KIA
for i in range (1,10):
    url=f'https://www.otomoto.pl/osobowe/kia?page=i'
    response=requests.get(url)
    response=response.content
    soup=BeautifulSoup(response,'html.parser')
    div=soup.find('div',class_="ooa-r53y0q ezh3mkl11")
    articles=div.find_all('article',class_='ooa-yca59n eszxync0')
    for article in articles:
                                               #name
        name=article.find('a').text
        print(name)
                                               #space
        space=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        space=space[:9]
        print(space)
                                               # kilometers
        km=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        km=km[13:18]
        print(km)
                                               #price
        price=article.find('h3',class_='eszxync16 ooa-1n2paoq er34gjf0').text
        price+=article.find('p',class_='eszxync17 ooa-8vn6i7 er34gjf0').text
        print(price)
      #                                          #kilometrage
        kilometrage=article.find('dd',class_='ooa-1omlbtp eszxync13').text
        print(kilometrage)
                                               #essence

        essence=article.find('dl', class_="ooa-1omlbtp eszxync13")
        essence=article.find(attrs={'data-parameter':"fuel_type"}).text.strip()
        print(essence)
                                               # gearbox_type==manuelle ou automatique

        gearbox_type=article.find('dl', class_="ooa-1omlbtp eszxync13")
        gearbox_type=article.find(attrs={'data-parameter':'gearbox'}).text.strip()
        print(gearbox_type)
                                      # year

        year=article.find('dl', class_="ooa-1omlbtp eszxync13")
        year=article.find(attrs={'data-parameter':'year'}).text.strip()
        print(year)

        cars.append([name,space,km,price,kilometrage,essence,gearbox_type,year])


                                                    #MAZDA
for i in range (1,10):
    url=f'https://www.otomoto.pl/osobowe/mazda?page=i'
    response=requests.get(url)
    response=response.content
    soup=BeautifulSoup(response,'html.parser')
    div=soup.find('div',class_="ooa-r53y0q ezh3mkl11")
    articles=div.find_all('article',class_='ooa-yca59n eszxync0')
    for article in articles:
                                               #name
        name=article.find('a').text
        print(name)
                                               #space
        space=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        space=space[:9]
        print(space)
                                               # kilometers
        km=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        km=km[13:18]
        print(km)
                                               #price
        price=article.find('h3',class_='eszxync16 ooa-1n2paoq er34gjf0').text
        price+=article.find('p',class_='eszxync17 ooa-8vn6i7 er34gjf0').text
        print(price)
      #                                          #kilometrage
        kilometrage=article.find('dd',class_='ooa-1omlbtp eszxync13').text
        print(kilometrage)
                                               #essence

        essence=article.find('dl', class_="ooa-1omlbtp eszxync13")
        essence=article.find(attrs={'data-parameter':"fuel_type"}).text.strip()
        print(essence)
                                               # gearbox_type==manuelle ou automatique

        gearbox_type=article.find('dl', class_="ooa-1omlbtp eszxync13")
        gearbox_type=article.find(attrs={'data-parameter':'gearbox'}).text.strip()
        print(gearbox_type)
                                      # year

        year=article.find('dl', class_="ooa-1omlbtp eszxync13")
        year=article.find(attrs={'data-parameter':'year'}).text.strip()
        print(year)

        cars.append([name,space,km,price,kilometrage,essence,gearbox_type,year])

                                                    #OPEL
for i in range (1,10):
    url=f'https://www.otomoto.pl/osobowe/opel?page=i'
    response=requests.get(url)
    response=response.content
    soup=BeautifulSoup(response,'html.parser')
    div=soup.find('div',class_="ooa-r53y0q ezh3mkl11")
    articles=div.find_all('article',class_='ooa-yca59n eszxync0')
    for article in articles:
                                               #name
        name=article.find('a').text
        print(name)
                                               #space
        space=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        space=space[:9]
        print(space)
                                               # kilometers
        km=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        km=km[13:18]
        print(km)
                                               #price
        price=article.find('h3',class_='eszxync16 ooa-1n2paoq er34gjf0').text
        price+=article.find('p',class_='eszxync17 ooa-8vn6i7 er34gjf0').text
        print(price)
      #                                          #kilometrage
        kilometrage=article.find('dd',class_='ooa-1omlbtp eszxync13').text
        print(kilometrage)
                                               #essence

        essence=article.find('dl', class_="ooa-1omlbtp eszxync13")
        essence=article.find(attrs={'data-parameter':"fuel_type"}).text.strip()
        print(essence)
                                               # gearbox_type==manuelle ou automatique

        gearbox_type=article.find('dl', class_="ooa-1omlbtp eszxync13")
        gearbox_type=article.find(attrs={'data-parameter':'gearbox'}).text.strip()
        print(gearbox_type)
                                      # year

        year=article.find('dl', class_="ooa-1omlbtp eszxync13")
        year=article.find(attrs={'data-parameter':'year'}).text.strip()
        print(year)

        cars.append([name,space,km,price,kilometrage,essence,gearbox_type,year])

                                                          #PEUGEOT

for i in range (1,10):
    url=f'https://www.otomoto.pl/osobowe/peugeot?page=i'
    response=requests.get(url)
    response=response.content
    soup=BeautifulSoup(response,'html.parser')
    div=soup.find('div',class_="ooa-r53y0q ezh3mkl11")
    articles=div.find_all('article',class_='ooa-yca59n eszxync0')
    for article in articles:
                                               #name
        name=article.find('a').text
        print(name)
                                               #space
        space=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        space=space[:9]
        print(space)
                                               # kilometers
        km=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        km=km[13:18]
        print(km)
                                               #price
        price=article.find('h3',class_='eszxync16 ooa-1n2paoq er34gjf0').text
        price+=article.find('p',class_='eszxync17 ooa-8vn6i7 er34gjf0').text
        print(price)
      #                                          #kilometrage
        kilometrage=article.find('dd',class_='ooa-1omlbtp eszxync13').text
        print(kilometrage)
                                               #essence

        essence=article.find('dl', class_="ooa-1omlbtp eszxync13")
        essence=article.find(attrs={'data-parameter':"fuel_type"}).text.strip()
        print(essence)
                                               # gearbox_type==manuelle ou automatique

        gearbox_type=article.find('dl', class_="ooa-1omlbtp eszxync13")
        gearbox_type=article.find(attrs={'data-parameter':'gearbox'}).text.strip()
        print(gearbox_type)
                                      # year

        year=article.find('dl', class_="ooa-1omlbtp eszxync13")
        year=article.find(attrs={'data-parameter':'year'}).text.strip()
        print(year)

        cars.append([name,space,km,price,kilometrage,essence,gearbox_type,year])

                                                            #RENAULT
for i in range (1,10):
    url=f'https://www.otomoto.pl/osobowe/renault?page=i'
    response=requests.get(url)
    response=response.content
    soup=BeautifulSoup(response,'html.parser')
    div=soup.find('div',class_="ooa-r53y0q ezh3mkl11")
    articles=div.find_all('article',class_='ooa-yca59n eszxync0')
    for article in articles:
                                               #name
        name=article.find('a').text
        print(name)
                                               #space
        space=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        space=space[:9]
        print(space)
                                               # kilometers
        km=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        km=km[13:18]
        print(km)
                                               #price
        price=article.find('h3',class_='eszxync16 ooa-1n2paoq er34gjf0').text
        price+=article.find('p',class_='eszxync17 ooa-8vn6i7 er34gjf0').text
        print(price)
      #                                          #kilometrage
        kilometrage=article.find('dd',class_='ooa-1omlbtp eszxync13').text
        print(kilometrage)
                                               #essence

        essence=article.find('dl', class_="ooa-1omlbtp eszxync13")
        essence=article.find(attrs={'data-parameter':"fuel_type"}).text.strip()
        print(essence)
                                               # gearbox_type==manuelle ou automatique

        gearbox_type=article.find('dl', class_="ooa-1omlbtp eszxync13")
        gearbox_type=article.find(attrs={'data-parameter':'gearbox'}).text.strip()
        print(gearbox_type)
                                      # year

        year=article.find('dl', class_="ooa-1omlbtp eszxync13")
        year=article.find(attrs={'data-parameter':'year'}).text.strip()
        print(year)

        cars.append([name,space,km,price,kilometrage,essence,gearbox_type,year])

                                                          #SEAT
for i in range (1,10):
    url=f'https://www.otomoto.pl/osobowe/seat?page=i'
    response=requests.get(url)
    response=response.content
    soup=BeautifulSoup(response,'html.parser')
    div=soup.find('div',class_="ooa-r53y0q ezh3mkl11")
    articles=div.find_all('article',class_='ooa-yca59n eszxync0')
    for article in articles:
                                               #name
        name=article.find('a').text
        print(name)
                                               #space
        space=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        space=space[:9]
        print(space)
                                               # kilometers
        km=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        km=km[13:18]
        print(km)
                                               #price
        price=article.find('h3',class_='eszxync16 ooa-1n2paoq er34gjf0').text
        price+=article.find('p',class_='eszxync17 ooa-8vn6i7 er34gjf0').text
        print(price)
      #                                          #kilometrage
        kilometrage=article.find('dd',class_='ooa-1omlbtp eszxync13').text
        print(kilometrage)
                                               #essence

        essence=article.find('dl', class_="ooa-1omlbtp eszxync13")
        essence=article.find(attrs={'data-parameter':"fuel_type"}).text.strip()
        print(essence)
                                               # gearbox_type==manuelle ou automatique

        gearbox_type=article.find('dl', class_="ooa-1omlbtp eszxync13")
        gearbox_type=article.find(attrs={'data-parameter':'gearbox'}).text.strip()
        print(gearbox_type)
                                      # year

        year=article.find('dl', class_="ooa-1omlbtp eszxync13")
        year=article.find(attrs={'data-parameter':'year'}).text.strip()
        print(year)

        cars.append([name,space,km,price,kilometrage,essence,gearbox_type,year])


                                                              #SKODA
for i in range (1,10):
    url=f'https://www.otomoto.pl/osobowe/skoda?page=i'
    response=requests.get(url)
    response=response.content
    soup=BeautifulSoup(response,'html.parser')
    div=soup.find('div',class_="ooa-r53y0q ezh3mkl11")
    articles=div.find_all('article',class_='ooa-yca59n eszxync0')
    for article in articles:
                                               #name
        name=article.find('a').text
        print(name)
                                               #space
        space=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        space=space[:9]
        print(space)
                                               # kilometers
        km=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        km=km[13:18]
        print(km)
                                               #price
        price=article.find('h3',class_='eszxync16 ooa-1n2paoq er34gjf0').text
        price+=article.find('p',class_='eszxync17 ooa-8vn6i7 er34gjf0').text
        print(price)
      #                                          #kilometrage
        kilometrage=article.find('dd',class_='ooa-1omlbtp eszxync13').text
        print(kilometrage)
                                               #essence

        essence=article.find('dl', class_="ooa-1omlbtp eszxync13")
        essence=article.find(attrs={'data-parameter':"fuel_type"}).text.strip()
        print(essence)
                                               # gearbox_type==manuelle ou automatique

        gearbox_type=article.find('dl', class_="ooa-1omlbtp eszxync13")
        gearbox_type=article.find(attrs={'data-parameter':'gearbox'}).text.strip()
        print(gearbox_type)
                                      # year

        year=article.find('dl', class_="ooa-1omlbtp eszxync13")
        year=article.find(attrs={'data-parameter':'year'}).text.strip()
        print(year)

        cars.append([name,space,km,price,kilometrage,essence,gearbox_type,year])

                                                      #TOYOTA
for i in range (1,10):
    url=f'https://www.otomoto.pl/osobowe/toyota?page=i'
    response=requests.get(url)
    response=response.content
    soup=BeautifulSoup(response,'html.parser')
    div=soup.find('div',class_="ooa-r53y0q ezh3mkl11")
    articles=div.find_all('article',class_='ooa-yca59n eszxync0')
    for article in articles:
                                               #name
        name=article.find('a').text
        print(name)
                                               #space
        space=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        space=space[:9]
        print(space)
                                               # kilometers
        km=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        km=km[13:18]
        print(km)
                                               #price
        price=article.find('h3',class_='eszxync16 ooa-1n2paoq er34gjf0').text
        price+=article.find('p',class_='eszxync17 ooa-8vn6i7 er34gjf0').text
        print(price)
      #                                          #kilometrage
        kilometrage=article.find('dd',class_='ooa-1omlbtp eszxync13').text
        print(kilometrage)
                                               #essence

        essence=article.find('dl', class_="ooa-1omlbtp eszxync13")
        essence=article.find(attrs={'data-parameter':"fuel_type"}).text.strip()
        print(essence)
                                               # gearbox_type==manuelle ou automatique

        gearbox_type=article.find('dl', class_="ooa-1omlbtp eszxync13")
        gearbox_type=article.find(attrs={'data-parameter':'gearbox'}).text.strip()
        print(gearbox_type)
                                      # year

        year=article.find('dl', class_="ooa-1omlbtp eszxync13")
        year=article.find(attrs={'data-parameter':'year'}).text.strip()
        print(year)

        cars.append([name,space,km,price,kilometrage,essence,gearbox_type,year])



                                                          #VOLVO
for i in range (1,10):
    url=f'https://www.otomoto.pl/osobowe/volvo?page=i'
    response=requests.get(url)
    response=response.content
    soup=BeautifulSoup(response,'html.parser')
    div=soup.find('div',class_="ooa-r53y0q ezh3mkl11")
    articles=div.find_all('article',class_='ooa-yca59n eszxync0')
    for article in articles:
                                               #name
        name=article.find('a').text
        print(name)
                                               #space
        space=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        space=space[:9]
        print(space)
                                               # kilometers
        km=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        km=km[13:18]
        print(km)
                                               #price
        price=article.find('h3',class_='eszxync16 ooa-1n2paoq er34gjf0').text
        price+=article.find('p',class_='eszxync17 ooa-8vn6i7 er34gjf0').text
        print(price)
      #                                          #kilometrage
        kilometrage=article.find('dd',class_='ooa-1omlbtp eszxync13').text
        print(kilometrage)
                                               #essence

        essence=article.find('dl', class_="ooa-1omlbtp eszxync13")
        essence=article.find(attrs={'data-parameter':"fuel_type"}).text.strip()
        print(essence)
                                               # gearbox_type==manuelle ou automatique

        gearbox_type=article.find('dl', class_="ooa-1omlbtp eszxync13")
        gearbox_type=article.find(attrs={'data-parameter':'gearbox'}).text.strip()
        print(gearbox_type)
                                      # year

        year=article.find('dl', class_="ooa-1omlbtp eszxync13")
        year=article.find(attrs={'data-parameter':'year'}).text.strip()
        print(year)

        cars.append([name,space,km,price,kilometrage,essence,gearbox_type,year])

                                                         #DACIA

for i in range (1,10):
    url=f'https://www.otomoto.pl/osobowe/dacia?page=i'
    response=requests.get(url)
    response=response.content
    soup=BeautifulSoup(response,'html.parser')
    div=soup.find('div',class_="ooa-r53y0q ezh3mkl11")
    articles=div.find_all('article',class_='ooa-yca59n eszxync0')
    for article in articles:
                                               #name
        name=article.find('a').text
        print(name)
                                               #space
        space=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        space=space[:9]
        print(space)
                                               # kilometers
        km=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        km=km[13:18]
        print(km)
                                               #price
        price=article.find('h3',class_='eszxync16 ooa-1n2paoq er34gjf0').text
        price+=article.find('p',class_='eszxync17 ooa-8vn6i7 er34gjf0').text
        print(price)
      #                                          #kilometrage
        kilometrage=article.find('dd',class_='ooa-1omlbtp eszxync13').text
        print(kilometrage)
                                               #essence

        essence=article.find('dl', class_="ooa-1omlbtp eszxync13")
        essence=article.find(attrs={'data-parameter':"fuel_type"}).text.strip()
        print(essence)
                                               # gearbox_type==manuelle ou automatique

        gearbox_type=article.find('dl', class_="ooa-1omlbtp eszxync13")
        gearbox_type=article.find(attrs={'data-parameter':'gearbox'}).text.strip()
        print(gearbox_type)
                                      # year

        year=article.find('dl', class_="ooa-1omlbtp eszxync13")
        year=article.find(attrs={'data-parameter':'year'}).text.strip()
        print(year)

        cars.append([name,space,km,price,kilometrage,essence,gearbox_type,year])

                                                       #mercedes-benz

for i in range (1,10):
    url=f'https://www.otomoto.pl/osobowe/mercedes-benz?page=i'
    response=requests.get(url)
    response=response.content
    soup=BeautifulSoup(response,'html.parser')
    div=soup.find('div',class_="ooa-r53y0q ezh3mkl11")
    articles=div.find_all('article',class_='ooa-yca59n eszxync0')
    for article in articles:
                                               #name
        name=article.find('a').text
        print(name)
                                               #space
        space=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        space=space[:9]
        print(space)
                                               # kilometers
        km=article.find('p',class_='eszxync10 ooa-1tku07r er34gjf0').text
        km=km[13:18]
        print(km)
                                               #price
        price=article.find('h3',class_='eszxync16 ooa-1n2paoq er34gjf0').text
        price+=article.find('p',class_='eszxync17 ooa-8vn6i7 er34gjf0').text
        print(price)
      #                                          #kilometrage
        kilometrage=article.find('dd',class_='ooa-1omlbtp eszxync13').text
        print(kilometrage)
                                               #essence

        essence=article.find('dl', class_="ooa-1omlbtp eszxync13")
        essence=article.find(attrs={'data-parameter':"fuel_type"}).text.strip()
        print(essence)
                                               # gearbox_type==manuelle ou automatique

        gearbox_type=article.find('dl', class_="ooa-1omlbtp eszxync13")
        gearbox_type=article.find(attrs={'data-parameter':'gearbox'}).text.strip()
        print(gearbox_type)
                                      # year

        year=article.find('dl', class_="ooa-1omlbtp eszxync13")
        year=article.find(attrs={'data-parameter':'year'}).text.strip()
        print(year)

        cars.append([name,space,km,price,kilometrage,essence,gearbox_type,year])

df=pd.DataFrame(cars,columns=['Car_Name','Engine capacity','Power','Price','Mileage','Fuel_Type','Gearbox_Type','Year_Of_Production'])
df.to_csv('CARS.csv')